permalink: /:year:month:day/:title
url: https://storage-mov-sp.unigon.net
baseurl: 

# variables
name: C:/MOV/SERVERS/PRIVATE/HOST/IUPDSC
description: PRIVATELY HOSTED IUPDSC STORAGE FOR THE MOV (The Republic of the Spacescraper)
google_verification: null


# File management
include: [".htaccess"]
exclude: ["README.md", "LICENSE"]

# Sass
sass:
  style: :compressed
  sass_dir: _sass

# Markdown
markdown: kramdown
kramdown:
  input: GFM
  syntax_highlighter_opts:
    disable : true